### ISSUE TITLE
simComm: return covariate values?

### ISSUE THREAD

**Issue by jniedballa** [mikemeredith/AHMbook#5]
Hi, 
in simComm(), would it please be possible to return the covariates "habitat" and "wind" automatically? From what I see the covariates can only be created by running simComm with a seed:

```
set.seed(2)
com <- simComm(...)
```

and then re-running the calls from inside simComm with the same seed:
```
set.seed(2)
habitat <- sort(rnorm(30))
wind <- matrix(rnorm(30 * 3), ncol=3)
```

which is slightly inconvenient for testing things. So, if possible, it would be great if the covariates would be returned as in the other sim... functions.
Thank you, and best regards,
Jürgen

**Comment by mikemeredith** [comment]
Thanks Jürgen! They should have been in the output from the start. Now fixed in the GitHub version 0.2.3.9000.

Don't know when then next roll up for CRAN will be. `simComm` has been there for 5 years and you're the first to report the problem,  so maybe wait for a few more bugs fixes.

Regards, Mike
